const router = require("express").Router();
const c = require("../controllers/offerController");
const auth = require("../middleware/authMiddleware");
const organizer = require("../middleware/requireOrganizer");
router.get("/", c.list("public"));
router.get("/mine", auth, organizer, c.list("mine"));
router.get("/mine/:id", auth, organizer, c.detail(true));
router.post("/", auth, organizer, c.save());
router.put("/:id", auth, organizer, c.save(true));
router.delete("/:id", auth, organizer, c.remove);
router.get("/:id", c.detail());
module.exports = router;
